[build]
# Enable native CPU optimizations for maximum performance
# This enables all available instruction sets on the target CPU (AVX2, AVX-512, etc.)
rustflags = [
    "-C", "target-cpu=native",        # Optimize for the specific CPU
    "-C", "target-feature=+crt-static", # Static linking for better performance
]

[target.x86_64-pc-windows-msvc]
# Windows-specific optimizations
rustflags = [
    "-C", "target-cpu=native",
    "-C", "target-feature=+crt-static",
    "-C", "link-arg=/OPT:REF",        # Remove unreferenced functions
    "-C", "link-arg=/OPT:ICF",        # Identical COMDAT folding
]

[target.x86_64-unknown-linux-gnu]
# Linux-specific optimizations (if you ever compile on Linux)
rustflags = [
    "-C", "target-cpu=native",
    "-C", "target-feature=+crt-static",
] 